#!/bin/bash
# THIS WAS WORKING PROPERLY, THEN IT DECIDED NOT TO, SUPPOSED TO MAKE CORRESPONDING TRANSACTION FILES FOR EACH RUN OF THE PROGRAM, ONLY MAKES ONE THOUGH!
#pick directory for the loop
FILES="inputs/*.txt"
num=0
for f in $FILES # loop through each file
do
  {
    java main accounts.txt rentalunits.txt < "$f"     #execute inputfiles into java program and crate output files
  } > "console_acc_output/consoleout_$((num++)).txt" ## store the stdout

done